# Generated by Django 5.2.12 on 2026-04-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0004_product_variant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, db_column='product_variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', True)), fields=('cart', 'product'), name='uniq_cart_product_no_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', False)), fields=('cart', 'product_variant'), name='uniq_cart_product_variant'),
        ),
    ]
