# Generated by Django 5.2.12 on 2026-04-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_variant'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, db_column='product_variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
