# Generated by Django 5.2.12 on 2026-03-29 13:16

import django.db.models.deletion
from django.db import migrations, models


def seed_default_variants(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for p in Product.objects.all():
        if ProductVariant.objects.filter(product_id=p.pk).exists():
            continue
        ProductVariant.objects.create(
            product_id=p.pk,
            color="#000000",
            size="Medium",
            stock=p.stock or 0,
        )


def unseed_default_variants(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    ProductVariant.objects.filter(color="#000000", size="Medium").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_dress_style_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Mã màu (vd hex #00C129) khớp filter frontend.', max_length=32)),
                ('size', models.CharField(max_length=40)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'product_variants',
                'indexes': [models.Index(fields=['product'], name='idx_pv_product'), models.Index(fields=['color'], name='idx_pv_color'), models.Index(fields=['size'], name='idx_pv_size')],
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'size'), name='uq_product_variants_product_color_size')],
            },
        ),
        migrations.RunPython(seed_default_variants, unseed_default_variants),
    ]
