# Generated by Django 5.2.7 on 2025-10-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="example",
            table="example",
        ),
    ]
